name: "dh-api-dev"

services:
  postgres:
    container_name: dh-api-db-dev
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dhapi'
      - 'POSTGRES_PASSWORD=localpassword'
      - 'POSTGRES_USER=dhapi'
    ports:
      - '8081:5432'