version: '3.6'

services:
  app:
    container_name: rentstudio-api-prod
    image: rentstudio-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    hostname: host-rentstudio-api-prod
    depends_on:
      - postgres
    env_file:
      - .prod.env
    ports:
      - "6060:8080"

  postgres:
    image: postgres
    restart: always
    container_name: rentstudio-db-prod
    hostname: host-rentstudio-db
    env_file:
      - .prod.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/log:/var/log/postgresql
    ports:
      - "6061:5432"
  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
