version: '3.1'

services:
  app:
    container_name: dh-backend-spring
    image: digitalhouse-pi:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "6060:8080"

  postgres:
    image: postgres
    restart: always
    container_name: dh-backend-postgres
    hostname: host-postgres-digitalhouse-spring
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: localpassword
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/log:/var/log/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6061:5432"

  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app