version: '3.6'

services:
  app:
    container_name: dh-backend-spring
    image: digitalhouse-pi:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - postgres
    environment:
      - SPRING_LOGGIN_LEVEL_ROOT=INFO
      - SPRING_LOGGIN_LEVEL_FRAMEWORK=INFO
      - SPRING_LOGGIN_LEVEL_PROJECT=DEBUG
    env_file:
      - .env
    ports:
      - "6060:8080"
    networks:
      - nginx_webnet

  postgres:
    image: postgres
    restart: always
    container_name: dh-backend-postgres
    hostname: host-postgres-digitalhouse-spring
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: proyectointegrador
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/log:/var/log/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6061:5432"
    networks:
      - nginx_webnet

  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

networks:
  nginx_webnet:
    external: true
