ALTER TABLE categories_features
DROP
CONSTRAINT fk_profea_on_product_feature;

ALTER TABLE category_features
DROP
CONSTRAINT fk_propol_on_product;

ALTER TABLE category_features
DROP
CONSTRAINT fk_propol_on_product_policy;

ALTER TABLE categories_features
DROP
CONSTRAINT fk_proprofea_on_product;

ALTER TABLE categories_features
    ADD category_id BIGINT;

ALTER TABLE categories_features
    ADD feature_id BIGINT;

ALTER TABLE categories_policies
    ADD category_id BIGINT;

ALTER TABLE categories_policies
    ADD policy_id BIGINT;

ALTER TABLE category_features
    ADD description VARCHAR(300);

ALTER TABLE category_features
    ADD icon VARCHAR(255);

ALTER TABLE category_features
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE category_features
    ADD name VARCHAR(30);

ALTER TABLE category_features
    ALTER COLUMN icon SET NOT NULL;

ALTER TABLE category_features
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE categories_features
    ADD CONSTRAINT fk_catfea_on_category_feature FOREIGN KEY (feature_id) REFERENCES category_features (id);

ALTER TABLE categories_features
    ADD CONSTRAINT fk_catfea_on_product_category FOREIGN KEY (category_id) REFERENCES product_category (id);

ALTER TABLE categories_policies
    ADD CONSTRAINT fk_catpol_on_category_policy FOREIGN KEY (policy_id) REFERENCES product_policies (id);

ALTER TABLE categories_policies
    ADD CONSTRAINT fk_catpol_on_product_category FOREIGN KEY (category_id) REFERENCES product_category (id);

ALTER TABLE categories_features
DROP
COLUMN features_id;

ALTER TABLE categories_features
DROP
COLUMN product_id;

ALTER TABLE categories_policies
DROP
COLUMN id;

ALTER TABLE categories_policies
DROP
COLUMN description;

ALTER TABLE categories_policies
DROP
COLUMN icon;

ALTER TABLE categories_policies
DROP
COLUMN name;

ALTER TABLE category_features
DROP
COLUMN policy_id;

ALTER TABLE category_features
DROP
COLUMN product_id;

ALTER TABLE categories_features
    ADD CONSTRAINT pk_categories_features PRIMARY KEY (category_id, feature_id);

ALTER TABLE categories_policies
    ADD CONSTRAINT pk_categories_policies PRIMARY KEY (category_id, policy_id);

ALTER TABLE category_features
    ADD CONSTRAINT pk_category_features PRIMARY KEY (id);
