name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DONWEB_SSH_PRIVATE_KEY }}

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.DONWEB_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.DONWEB_SSH_HOST }}
          SERVER_USER: ${{ secrets.DONWEB_SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'cd /root/docker-apps/digitalhouse/backend && git pull origin main && ./start_containers.sh'
