name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DONWEB_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_rsa
          chmod 600 ~/.ssh/github_actions_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_actions_rsa

      - name: Add server to known hosts
        run: ssh-keyscan -p5664 -H ${{ secrets.DONWEB_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.DONWEB_SSH_HOST }}
          SERVER_USER: ${{ secrets.DONWEB_SSH_USERNAME }}
        run: |
          ssh -p5664 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'cd /root/docker-apps/digitalhouse/backend && git pull origin main && ./start_containers.sh'
